Consolidate open and open_create function typedef's
The open() function is defined as a variac function
int open(const char *, int, ...)
here
https://pubs.opengroup.org/onlinepubs/009695399/functions/open.html

So it is not necessary to have two typedefs.

Fixes this compile error on RHEL 8.2 + gcc 8.3

.../opae-sdk/external/opae-test/framework/mock/test_system.cpp: In constructor ‘opae::testing::test_system::test_system()’:
.../opae-sdk/external/opae-test/framework/mock/test_system.cpp:191:36: error: cast between incompatible function types from ‘opae::testing::test_system::open_func’ {aka ‘int (*)(const char*, int)’} to ‘opae::testing::test_system::open_create_func’ {aka ‘int (*)(const char*, int, unsigned int)’} [-Werror=cast-function-type]

Signed-off-by: Tom Rix <trix@redhat.com>